model_path: /model/is/here
src_lang: en
trg_lang: fr
framework: fairseq
decoder: 
   BeamSearch:
      some_param_1: 1.07
preprocessor:
   - MosesTokenizer:
      some_param_1: 1.07
   - SPMPreprocessor:
      some_param_1: 0.77
      some_param_2: 1.09
postprocessor:
   - SPMPostprocessor
   - MosesDetokenizer
